name: Release

on:
    workflow_dispatch:

env:
    SIGNING_KEYSTORE_FILENAME: signing_key.jks
    BUILD_APK_FILE: ./app/build/outputs/apk/release/app-release.apk

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: npm

            - uses: actions/setup-java@v3
              with:
                  distribution: zulu
                  java-version: 17
                  cache: gradle

            - name: 🚧 Do prerequisites
              run: npm ci

            - name: 🔢 Get version
              id: app_version
              run: echo "version=$(npm run version:print --silent)" >> $GITHUB_OUTPUT

            - name: 🔎 Check for release
              uses: actions/github-script@v6
              env:
                  APP_VERSION_NAME: ${{ steps.app_version.outputs.version }}
              with:
                  script: |
                      const tagName = `v${process.env["APP_VERSION_NAME"]}`;
                      let statusCode;
                      try {
                          const result = await github.rest.repos.getReleaseByTag({
                              tag: tagName,
                              owner: context.repo.owner,
                              repo: context.repo.repo,
                          });
                          statusCode = result.status;
                      } catch (err) {
                          statusCode = err.status;
                      }
                      if (statusCode !== 404) {
                          throw new Error(`${tagName} tag already exists (received status code: ${statusCode})`);
                      }

            - name: 🔨 Generate certificate
              run: echo $SIGNING_KEYSTORE_FILE_CONTENT | base64 -di > $SIGNING_KEYSTORE_FILE
              env:
                  SIGNING_KEYSTORE_FILE: ./${{ env.SIGNING_KEYSTORE_FILENAME }}
                  SIGNING_KEYSTORE_FILE_CONTENT: ${{ secrets.SIGNING_KEYSTORE_FILE }}

            - name: 🔨 Build apk
              run: |
                  npm run prebuild
                  chmod +x ./gradlew
                  ./gradlew build
              env:
                  SIGNING_KEYSTORE_FILE: ../${{ env.SIGNING_KEYSTORE_FILENAME }}
                  SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
                  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

            - name: 📝 Rename apk
              uses: actions/github-script@v6
              id: app_binary
              env:
                  APP_VERSION_NAME: ${{ steps.app_version.outputs.version }}
              with:
                  result-encoding: string
                  script: |
                      const fs = require("fs");
                      const path = require("path");
                      const buildApkFile = process.env["BUILD_APK_FILE"];
                      const appVersionName = process.env["APP_VERSION_NAME"];
                      const releaseApkFile = path.join(
                          buildApkFile, `../symphony-v${appVersionName}.apk`
                      );
                      fs.copyFileSync(buildApkFile, releaseApkFile);
                      return releaseApkFile;

            - name: 🚀 Upload apk
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ steps.app_version.outputs.version }}
                  artifacts: ${{ steps.app_binary.outputs.result }}
                  generateReleaseNotes: true
                  draft: true
                  artifactErrorsFailBuild: true
